### ISSUE TITLE
Possibility to schedule a recurring maintenance

### ISSUE THREAD

**Issue by michele-grifa** [churchportal/laravel-scheduled-maintenance#1]
It is possible to schedule a maintenance every day at the same hours?

**Comment by jamesburrow23** [comment]
@michele-grifa sorry for the really late response here, I somehow missed your comment.

It's not currently a feature natively supported by this package but  you could create a scheduled job that would create a new schedule maintenance entry every day

**Comment by michele-grifa** [comment]
Thanks.
